#!/bin/bash

HOME=$(pwd)
FILE=app-7.wget
echo "# This file auto generated by $0" >> filelist

i=101
echo xinit-1.4.1.tar.gz >> $FILE

for file in $(grep -v '^#' $FILE)
do
	wget -q https://www.x.org/pub/individual/app/$file --no-check-certificate
	echo '' >> filelist
	echo "FILE$i= $file" >> filelist
	echo "URL-\$(FILE$i)= \$(URLBASE)/\$(FILE$i)" >> filelist
	echo "MD5-\$(FILE$i)= $(md5sum $file | awk '{print $1}')" >> filelist
	i=`expr $i + 1`
done

cd $HOME

