#!/bin/bash

HOME=$(pwd)
FILE="$(pwd)/lib-7.wget"

echo "# This file auto generated by $0" > filelist

i=101

echo libXfont-1.5.4.tar.bz2 >> $FILE

for file in $(grep -v '^#' $FILE)
do
	wget -q https://www.x.org/pub/individual/lib/$file --no-check-certificate
	echo '' >> filelist
	echo "FILE$i= $file" >> filelist
	echo "URL-\$(FILE$i)= \$(URLBASE)/\$(FILE$i)" >> filelist
	echo "MD5-\$(FILE$i)= $(md5sum $file | awk '{print $1}')" >> filelist
	i=`expr $i + 1`
done

